#!/bin/bash

alias flush='dscacheutil -flushcache'
alias ls='ls -Ga'
alias push="git push -u origin master"
alias hpush="git push heroku master"
alias commit="git commit -a -m "
alias http='python -m SimpleHTTPServer'
alias img='sips'
alias ts2dvd="mkisofs -f -dvd-video -udf -V DVD_VIDEO -o ~/Desktop/DVD_VIDEO.iso"
alias s="subl"
alias pf="open ./ -a Path\ Finder"
alias f="open ./ -a Finder"
alias vpn="ssh root@vpn.yasyf.com"
alias bpf="cd /Users/yasyf/Dropbox/Documents/bash/"
alias grep='grep --color=auto'
alias ..="cd .."
alias whois="whois -h whois-servers.net"
alias c="tr -d '\n' | pbcopy"
alias copy="c"
alias mail="/usr/bin/email"
alias terminal-notifier="/usr/bin/terminal-notifier.app/Contents/MacOS/terminal-notifier -message"
alias redir='curl -s -o /dev/null -I -w "HTTP_CODE: %{http_code}\nREDIRECT_URL: %{redirect_url}\n"'
alias checkgit="find ~ -type d -name .git | while read gitfolder;do echo $gitfolder; cd $gitfolder; cd ..; git --git-dir=$gitfolder status; push; done | mate"
alias rand="uuidgen"
alias pbgist="pbpaste | gist | xargs short | pbcopy"
alias lsusb="system_profiler SPUSBDataType"
alias speedtest="/Users/yasyf/Dropbox/Documents/Python\ Play/speedtest.py  --simple"
alias cat='pygmentize -O style=monokai -f console256 -g'
alias ccat='/bin/cat'
alias pbsms="pebble sms 'MacBook Pro'"
alias pbping="pebble ping"
alias sudo="sudo "
alias h="howdoi"
alias cdmit="cd '~/Dropbox (MIT)/'"
