#!/bin/bash
function zap() { open -a AppZapper /Applications/"${1}".app; }
function bp()
{
	local DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	local files="$(ls $DIR | grep -v master | grep -v README | grep -v git | tail -n +3)"
	
if [[ $1 && -f "$DIR/$1" ]]; then
	
	mate $DIR/$1
elif [[ $1 == "f" ]]; then
	pf $DIR
else
	mate ~/.bash_profile
fi
}
function json() {
	if [ -p /dev/stdin ]; then
		# piping, e.g. `echo '{"foo":42}' | json`
		python -mjson.tool | pygmentize -l javascript
	else
		# e.g. `json '{"foo":42}'`
		python -mjson.tool <<< "$*" | pygmentize -l javascript
	fi
}
function dataurl() {
	echo "data:image/${1##*.};base64,$(openssl base64 -in "$1")" | tr -d '\n'
}
function mail_local()
{
	open "mailto:$1?subject=$2&body=$3"
}
function ocr()
{
if [[ $1 ]]; then
	if [[ $2 ]]; then
		/usr/bin/takocr "$1" | tail -n +2 > "$2"
		mate "$2"
	else
		
		/usr/bin/takocr "$1" | tail -n +2 > ~/Desktop/"`basename "$1"`.ocr.txt" 
		mate ~/Desktop/"`basename "$1"`.ocr.txt" 
	fi 
else
	echo "Usage: ocr input.img output.html"
fi
}
function mail()
{
	show_usage()
	{
		echo "Usage: mail -t to_address -s subject -b body -f filename"

	}
	
	MINARGS=3
	case $1 in
		"-h"|"--help") show_usage; return 1; ;;
	esac
	
	ARGC=$#
	if [[ $ARGC -lt $MINARGS ]] ; then
	 echo "Too few arguments given (only attachment is optional)"
	 echo
	 show_usage
	return 1;
	fi
	


  while getopts "t:s:b:f:a:" optname
    do
      case "$optname" in
        "t")
			local to=($OPTARG)    
          ;;
		"s")
			local subject=("$OPTARG")          
	      ;;
        "b")
			local body=("$OPTARG")          
          ;;
		"f")
			local file=($OPTARG)          
	      ;;
		"a")
			local file=($OPTARG)          
	      ;;

        "?")
          echo "Unknown option $OPTARG"
          ;;
        ":")
          echo "No argument value for option $OPTARG"
          ;;
        *)
        # Should not occur
          echo "Unknown error while processing options"
			show_usage;return 1;
          ;;
      esac
    done
	 
	if [ "$to" ]; then echo ""; else echo "to address required";show_usage;return 1; fi
		if [ "$subject" ]; then echo ""; else echo "subject required";show_usage;return 1; fi
		if [ -p /dev/stdin ]; then local body=($(< /dev/stdin));elif [ "$body" ]; then echo ""; else echo "body required";show_usage;return 1; fi

curl -v -s -k --user api:key-0nr13p-uhgfajhvo1580eeeva017kma8 \
	    https://api.mailgun.net/v2/yasyfmohamedali.mailgun.org/messages \
	    -F from="Yasyf Mohamedali <$(whoami)@$(hostname)>" \
	    -F to="$to" \
	    -F subject="$subject" \
	    -F text="$body" \
	    -F attachment="$(if [ "$file" ]; then echo @$file; fi)"
	
	unset to
	unset subject
	unset body
	unset file
	unset optname
	unset OPTARG
	unset MINARGS
	unset ARGC
	return 0;
}

